import type { Metadata } from "next";
import "./globals.css";
import styles from './page.module.css';

export const metadata: Metadata = {
	title: "Мой проект - Главная	",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{/* children - это  React node (например, страницы с вложенным layout)*/}
				<nav className={styles.nav}>
					<ul>
						<li>Курсы</li>
						<li>О нас</li>
						<li>Для детей</li>
					</ul>
				</nav>
				<div>
					{children}
				</div>
			</body>
		</html>
	);
}
