import React from "react";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Мой проект - Авторизация",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{/* children - это  React node (например, страницы с вложенным layout)*/}
				<div>
                    Этот текст видно только если ты в корневом layoute для части сайта, которая отвечает за авторизация и т.д.
                    <div>
                        {children}
                    </div>
                </div>
			</body>
		</html>
	);
}
